name: Packaging
run-name: Build packages
on: [push]
jobs:
  rpm-packaging:
    name: RPM Packaging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build RPM packages for Fedora 41
        run: docker -v && exit 1
      - name: Generate artifact with built RPM packages
        uses: actions/upload-artifact@v4
        with:
          name: hid-nx-rpm
          path: ${{ github.workspace }}/*.rpm
          if-no-files-found: error
          overwrite: true
