name: Packaging
run-name: Build packages
on: [push]
jobs:
  rpm-packaging:
    name: RPM Packaging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build RPM packages
        uses: ./.github/actions/rpm-packaging
      - name: Upload RPM packages as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hid-nx-rpm
          path: ${{ github.workspace }}/*.rpm
          if-no-files-found: error
          overwrite: true